trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - template: azure-pipelines-build.yml

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - template: azure-pipelines-deploy.yml
