trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - template: azure-pipelines-build.yml

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
        - deployment: DeployJob
          displayName: 'Deploy to development'
          environment: 'development' # trigger for approval
          strategy:
              runOnce:
                deploy: 
                    steps:
                    - template: azure-pipelines-deploy.yml
